In [2]:
import pandas as pd

In [14]:
#criando dicionario
alunos = {"nome":["VISIONALDENSON","WANDOSVALDO","ADIABELSIO","UBERANTONIO"],
         "nota":[7,5.5,8,6.5],
         "Aprovado":["sim","não","sim","sim"]}


In [16]:
#criando dataframe a partir do dicionario
data = pd.DataFrame(alunos)

In [17]:
print(data)

        nome  nota Aprovado
0  GUILHERME   7.0      sim
1    RICARDO   5.5      não
2    DENISON   8.0      sim
3       LUIZ   6.5      sim


In [19]:
data.head(1)

nome  nota Aprovado
0  GUILHERME   7.0      sim

In [21]:
obj = pd.Series([2,6,9,10,5])

In [23]:
print(obj)

0     2
1     6
2     9
3    10
4     5
dtype: int64


In [29]:
import numpy as np
#array unidimencional
array = np.array([2,3,9,10,5])
print(array)

[ 2  3  9 10  5]


In [30]:
#array bidimencional
array2 = np.array([(2,3,9,10,5),(3,4,6,8,10)])
print(array2)

[[ 2  3  9 10  5]
 [ 3  4  6  8 10]]


In [41]:
array1 = np.array([2,3,9,10,5])

array2 = np.array([(2,3,9,10,5),(3,4,6,8,10)])

print(array)
print()
print(array2)

[ 2  3  9 10  5]

[[ 2  3  9 10  5]
 [ 3  4  6  8 10]]


In [42]:
#somente em arrays unidimencionais
obj2 = pd.Series(array1)

print(obj2)

0     2
1     3
2     9
3    10
4     5
dtype: int32
